name: 'metrics-drilldown'
services:
  grafana:
    container_name: 'grafana'
    user: root

    build:
      context: ../.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-latest}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3001:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/grafana-metricsdrilldown-app
      - ../provisioning:/etc/grafana/provisioning
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.grafana-metricsdrilldown-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-metricsdrilldown-app
      GF_SERVER_ROOT_URL: http://localhost:3001

  prometheus:
    container_name: 'prometheus'
    image: prom/prometheus:v3.1.0
    ports:
      - '9099:9090'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: >
      --enable-feature=remote-write-receiver
      --enable-feature=exemplar-storage
      --enable-feature=native-histograms
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
    volumes:
      - ../config/prometheus.yaml:/etc/prometheus/prometheus.yml
